/*******************************************************************************
*
* McStas, neutron ray-tracing package
*         Copyright 1997-2002, All rights reserved
*         Risoe National Laboratory, Roskilde, Denmark
*         Institut Laue Langevin, Grenoble, France
*
* Component: Semi_mirror
*
* %Identification
*
* Written by: Peter Willendrup
* Date: November 2025
* Origin: ISIS
*
* Semi-permeable mirror
*
* %Description
*
* %Parameters
* Input parameters:
*
* (none)
*
* %End
*******************************************************************************/

DEFINE COMPONENT Semi_mirror

SETTING PARAMETERS (zdepth=0.1, yheight=0.1,reflectivity=0.9,fraction=0.5)

/* Neutron parameters: (x,y,z,vx,vy,vz,t,sx,sy,sz,p) */
SHARE
%{
%}

USERVARS
%{
%}

DECLARE
%{
%}

INITIALIZE
%{
  if(!zdepth || !yheight){
    fprintf(stderr,"mirror has no area. Aborting\n");exit(-1);
  }
%}

TRACE
%{

   int internal_color;
   PROP_X0;
   internal_color=1;
   if (z<zdepth/2.0 && z>-zdepth/2.0 && y<yheight/2.0 && y>-yheight/2.0){
     internal_color=0;
     double r=rand01();
     if(r<=fraction){
       p*=reflectivity/fraction;
       vx=-vx;
     }else{
       p*=(1-reflectivity)/(1-fraction);
     }
   }
%}

SAVE
%{
%}

FINALLY
%{
%}

MCDISPLAY
%{
  /* A bit ugly; hard-coded dimensions. */
  magnify("");
  rectangle("yz",0,0,0,yheight,zdepth);
%}

END
